<?php

class Animalshelter_Breed_Dog {
	/**
	 * @var string[]
	 */
	private array $breeds;

	public function __construct() {
		$this->breeds = array(
			'unknown'                            => array( 'name' => __( 'Unknown', 'animal-shelter' ) ),
			'mutt'                               => array( 'name' => _x( 'Mutt', 'Breed of a dog', 'animal-shelter' ) ),
			'afador'                             => array( 'name' => _x( 'Afador', 'Breed of a dog', 'animal-shelter' ) ),
			'affenhuahua'                        => array( 'name' => _x( 'Affenhuahua', 'Breed of a dog', 'animal-shelter' ) ),
			'affenpinscher'                      => array( 'name' => _x( 'Affenpinscher', 'Breed of a dog', 'animal-shelter' ) ),
			'afghan-hound'                       => array( 'name' => _x( 'Afghan Hound', 'Breed of a dog', 'animal-shelter' ) ),
			'airedale-terrier'                   => array( 'name' => _x( 'Airedale Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'akbash'                             => array( 'name' => _x( 'Akbash', 'Breed of a dog', 'animal-shelter' ) ),
			'akita'                              => array( 'name' => _x( 'Akita', 'Breed of a dog', 'animal-shelter' ) ),
			'akita-chow'                         => array( 'name' => _x( 'Akita Chow', 'Breed of a dog', 'animal-shelter' ) ),
			'akita-pit'                          => array( 'name' => _x( 'Akita Pit', 'Breed of a dog', 'animal-shelter' ) ),
			'akita-shepherd'                     => array( 'name' => _x( 'Akita Shepherd', 'Breed of a dog', 'animal-shelter' ) ),
			'alaskan-klee-kai'                   => array( 'name' => _x( 'Alaskan Klee Kai', 'Breed of a dog', 'animal-shelter' ) ),
			'alaskan-malamute'                   => array( 'name' => _x( 'Alaskan Malamute', 'Breed of a dog', 'animal-shelter' ) ),
			'american-bulldog'                   => array( 'name' => _x( 'American Bulldog', 'Breed of a dog', 'animal-shelter' ) ),
			'american-english-coonhound'         => array( 'name' => _x( 'American English Coonhound', 'Breed of a dog', 'animal-shelter' ) ),
			'american-eskimo-dog'                => array( 'name' => _x( 'American Eskimo Dog', 'Breed of a dog', 'animal-shelter' ) ),
			'american-foxhound'                  => array( 'name' => _x( 'American Foxhound', 'Breed of a dog', 'animal-shelter' ) ),
			'american-hairless-terrier'          => array( 'name' => _x( 'American Hairless Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'american-leopard-hound'             => array( 'name' => _x( 'American Leopard Hound', 'Breed of a dog', 'animal-shelter' ) ),
			'american-pit-bull-terrier'          => array( 'name' => _x( 'American Pit Bull Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'american-pugabull'                  => array( 'name' => _x( 'American Pugabull', 'Breed of a dog', 'animal-shelter' ) ),
			'american-staffordshire-terrier'     => array( 'name' => _x( 'American Staffordshire Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'american-water-spaniel'             => array( 'name' => _x( 'American Water Spaniel', 'Breed of a dog', 'animal-shelter' ) ),
			'anatolian-shepherd-dog'             => array( 'name' => _x( 'Anatolian Shepherd Dog', 'Breed of a dog', 'animal-shelter' ) ),
			'appenzeller-sennenhunde'            => array( 'name' => _x( 'Appenzeller Sennenhunde', 'Breed of a dog', 'animal-shelter' ) ),
			'auggie'                             => array( 'name' => _x( 'Auggie', 'Breed of a dog', 'animal-shelter' ) ),
			'aussiedoodle'                       => array( 'name' => _x( 'Aussiedoodle', 'Breed of a dog', 'animal-shelter' ) ),
			'aussiepom'                          => array( 'name' => _x( 'Aussiepom', 'Breed of a dog', 'animal-shelter' ) ),
			'australian-cattle-dog'              => array( 'name' => _x( 'Australian Cattle Dog', 'Breed of a dog', 'animal-shelter' ) ),
			'australian-kelpie'                  => array( 'name' => _x( 'Australian Kelpie', 'Breed of a dog', 'animal-shelter' ) ),
			'australian-retriever'               => array( 'name' => _x( 'Australian Retriever', 'Breed of a dog', 'animal-shelter' ) ),
			'australian-shepherd'                => array( 'name' => _x( 'Australian Shepherd', 'Breed of a dog', 'animal-shelter' ) ),
			'australian-shepherd-husky'          => array( 'name' => _x( 'Australian Shepherd Husky', 'Breed of a dog', 'animal-shelter' ) ),
			'australian-shepherd-lab-mix'        => array( 'name' => _x( 'Australian Shepherd Lab Mix', 'Breed of a dog', 'animal-shelter' ) ),
			'australian-shepherd-pit-bull-mix'   => array( 'name' => _x( 'Australian Shepherd Pit Bull Mix', 'Breed of a dog', 'animal-shelter' ) ),
			'australian-stumpy-tail-cattle-dog'  => array( 'name' => _x( 'Australian Stumpy Tail Cattle Dog', 'Breed of a dog', 'animal-shelter' ) ),
			'australian-terrier'                 => array( 'name' => _x( 'Australian Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'azawakh'                            => array( 'name' => _x( 'Azawakh', 'Breed of a dog', 'animal-shelter' ) ),
			'barbet'                             => array( 'name' => _x( 'Barbet', 'Breed of a dog', 'animal-shelter' ) ),
			'basenji'                            => array( 'name' => _x( 'Basenji', 'Breed of a dog', 'animal-shelter' ) ),
			'bassador'                           => array( 'name' => _x( 'Bassador', 'Breed of a dog', 'animal-shelter' ) ),
			'basset-fauve-de-bretagne'           => array( 'name' => _x( 'Basset Fauve de Bretagne', 'Breed of a dog', 'animal-shelter' ) ),
			'basset-hound'                       => array( 'name' => _x( 'Basset Hound', 'Breed of a dog', 'animal-shelter' ) ),
			'basset-retriever'                   => array( 'name' => _x( 'Basset Retriever', 'Breed of a dog', 'animal-shelter' ) ),
			'bavarian-mountain-scent-hound'      => array( 'name' => _x( 'Bavarian Mountain Scent Hound', 'Breed of a dog', 'animal-shelter' ) ),
			'beabull'                            => array( 'name' => _x( 'Beabull', 'Breed of a dog', 'animal-shelter' ) ),
			'beagle'                             => array( 'name' => _x( 'Beagle', 'Breed of a dog', 'animal-shelter' ) ),
			'beaglier'                           => array( 'name' => _x( 'Beaglier', 'Breed of a dog', 'animal-shelter' ) ),
			'bearded-collie'                     => array( 'name' => _x( 'Bearded Collie', 'Breed of a dog', 'animal-shelter' ) ),
			'bedlington-terrier'                 => array( 'name' => _x( 'Bedlington Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'belgian-laekenois'                  => array( 'name' => _x( 'Belgian Laekenois', 'Breed of a dog', 'animal-shelter' ) ),
			'belgian-malinois'                   => array( 'name' => _x( 'Belgian Malinois', 'Breed of a dog', 'animal-shelter' ) ),
			'belgian-sheepdog'                   => array( 'name' => _x( 'Belgian Sheepdog', 'Breed of a dog', 'animal-shelter' ) ),
			'belgian-tervuren'                   => array( 'name' => _x( 'Belgian Tervuren', 'Breed of a dog', 'animal-shelter' ) ),
			'bergamasco-sheepdog'                => array( 'name' => _x( 'Bergamasco Sheepdog', 'Breed of a dog', 'animal-shelter' ) ),
			'berger-picard'                      => array( 'name' => _x( 'Berger Picard', 'Breed of a dog', 'animal-shelter' ) ),
			'bernedoodle'                        => array( 'name' => _x( 'Bernedoodle', 'Breed of a dog', 'animal-shelter' ) ),
			'bernese-mountain-dog'               => array( 'name' => _x( 'Bernese Mountain Dog', 'Breed of a dog', 'animal-shelter' ) ),
			'bichon-frise'                       => array( 'name' => _x( 'Bichon Frise', 'Breed of a dog', 'animal-shelter' ) ),
			'biewer-terrier'                     => array( 'name' => _x( 'Biewer Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'black-and-tan-coonhound'            => array( 'name' => _x( 'Black and Tan Coonhound', 'Breed of a dog', 'animal-shelter' ) ),
			'black-mouth-cur'                    => array( 'name' => _x( 'Black Mouth Cur', 'Breed of a dog', 'animal-shelter' ) ),
			'black-russian-terrier'              => array( 'name' => _x( 'Black Russian Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'bloodhound'                         => array( 'name' => _x( 'Bloodhound', 'Breed of a dog', 'animal-shelter' ) ),
			'blue-lacy'                          => array( 'name' => _x( 'Blue Lacy', 'Breed of a dog', 'animal-shelter' ) ),
			'bluetick-coonhound'                 => array( 'name' => _x( 'Bluetick Coonhound', 'Breed of a dog', 'animal-shelter' ) ),
			'bocker'                             => array( 'name' => _x( 'Bocker', 'Breed of a dog', 'animal-shelter' ) ),
			'boerboel'                           => array( 'name' => _x( 'Boerboel', 'Breed of a dog', 'animal-shelter' ) ),
			'boglen-terrier'                     => array( 'name' => _x( 'Boglen Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'bohemian-shepherd'                  => array( 'name' => _x( 'Bohemian Shepherd', 'Breed of a dog', 'animal-shelter' ) ),
			'bolognese'                          => array( 'name' => _x( 'Bolognese', 'Breed of a dog', 'animal-shelter' ) ),
			'borador'                            => array( 'name' => _x( 'Borador', 'Breed of a dog', 'animal-shelter' ) ),
			'border-collie'                      => array( 'name' => _x( 'Border Collie', 'Breed of a dog', 'animal-shelter' ) ),
			'border-sheepdog'                    => array( 'name' => _x( 'Border Sheepdog', 'Breed of a dog', 'animal-shelter' ) ),
			'border-terrier'                     => array( 'name' => _x( 'Border Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'bordoodle'                          => array( 'name' => _x( 'Bordoodle', 'Breed of a dog', 'animal-shelter' ) ),
			'borzoi'                             => array( 'name' => _x( 'Borzoi', 'Breed of a dog', 'animal-shelter' ) ),
			'boshih'                             => array( 'name' => _x( 'BoShih', 'Breed of a dog', 'animal-shelter' ) ),
			'bossie'                             => array( 'name' => _x( 'Bossie', 'Breed of a dog', 'animal-shelter' ) ),
			'boston-boxer'                       => array( 'name' => _x( 'Boston Boxer', 'Breed of a dog', 'animal-shelter' ) ),
			'boston-terrier'                     => array( 'name' => _x( 'Boston Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'boston-terrier-pekingese-mix'       => array( 'name' => _x( 'Boston Terrier Pekingese Mix', 'Breed of a dog', 'animal-shelter' ) ),
			'bouvier-des-flandres'               => array( 'name' => _x( 'Bouvier des Flandres', 'Breed of a dog', 'animal-shelter' ) ),
			'boxador'                            => array( 'name' => _x( 'Boxador', 'Breed of a dog', 'animal-shelter' ) ),
			'boxer'                              => array( 'name' => _x( 'Boxer', 'Breed of a dog', 'animal-shelter' ) ),
			'boxerdoodle'                        => array( 'name' => _x( 'Boxerdoodle', 'Breed of a dog', 'animal-shelter' ) ),
			'boxmatian'                          => array( 'name' => _x( 'Boxmatian', 'Breed of a dog', 'animal-shelter' ) ),
			'boxweiler'                          => array( 'name' => _x( 'Boxweiler', 'Breed of a dog', 'animal-shelter' ) ),
			'boykin-spaniel'                     => array( 'name' => _x( 'Boykin Spaniel', 'Breed of a dog', 'animal-shelter' ) ),
			'bracco-italiano'                    => array( 'name' => _x( 'Bracco Italiano', 'Breed of a dog', 'animal-shelter' ) ),
			'braque-du-bourbonnais'              => array( 'name' => _x( 'Braque du Bourbonnais', 'Breed of a dog', 'animal-shelter' ) ),
			'briard'                             => array( 'name' => _x( 'Briard', 'Breed of a dog', 'animal-shelter' ) ),
			'brittany'                           => array( 'name' => _x( 'Brittany', 'Breed of a dog', 'animal-shelter' ) ),
			'broholmer'                          => array( 'name' => _x( 'Broholmer', 'Breed of a dog', 'animal-shelter' ) ),
			'brussels-griffon'                   => array( 'name' => _x( 'Brussels Griffon', 'Breed of a dog', 'animal-shelter' ) ),
			'bugg'                               => array( 'name' => _x( 'Bugg', 'Breed of a dog', 'animal-shelter' ) ),
			'bull-arab'                          => array( 'name' => _x( 'Bull Arab', 'Breed of a dog', 'animal-shelter' ) ),
			'bull-terrier'                       => array( 'name' => _x( 'Bull Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'bullador'                           => array( 'name' => _x( 'Bullador', 'Breed of a dog', 'animal-shelter' ) ),
			'bullboxer-pit'                      => array( 'name' => _x( 'Bullboxer Pit', 'Breed of a dog', 'animal-shelter' ) ),
			'bulldog'                            => array( 'name' => _x( 'Bulldog', 'Breed of a dog', 'animal-shelter' ) ),
			'bullmastiff'                        => array( 'name' => _x( 'Bullmastiff', 'Breed of a dog', 'animal-shelter' ) ),
			'bullmatian'                         => array( 'name' => _x( 'Bullmatian', 'Breed of a dog', 'animal-shelter' ) ),
			'bull-pei'                           => array( 'name' => _x( 'Bull-Pei', 'Breed of a dog', 'animal-shelter' ) ),
			'cairn-terrier'                      => array( 'name' => _x( 'Cairn Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'canaan-dog'                         => array( 'name' => _x( 'Canaan Dog', 'Breed of a dog', 'animal-shelter' ) ),
			'cane-corso'                         => array( 'name' => _x( 'Cane Corso', 'Breed of a dog', 'animal-shelter' ) ),
			'cardigan-welsh-corgi'               => array( 'name' => _x( 'Cardigan Welsh Corgi', 'Breed of a dog', 'animal-shelter' ) ),
			'carolina-dog'                       => array( 'name' => _x( 'Carolina Dog', 'Breed of a dog', 'animal-shelter' ) ),
			'catahoula-bulldog'                  => array( 'name' => _x( 'Catahoula Bulldog', 'Breed of a dog', 'animal-shelter' ) ),
			'catahoula-leopard-dog'              => array( 'name' => _x( 'Catahoula Leopard Dog', 'Breed of a dog', 'animal-shelter' ) ),
			'caucasian-shepherd-dog'             => array( 'name' => _x( 'Caucasian Shepherd Dog', 'Breed of a dog', 'animal-shelter' ) ),
			'cavachon'                           => array( 'name' => _x( 'Cavachon', 'Breed of a dog', 'animal-shelter' ) ),
			'cavador'                            => array( 'name' => _x( 'Cavador', 'Breed of a dog', 'animal-shelter' ) ),
			'cav-a-jack'                         => array( 'name' => _x( 'Cav-a-Jack', 'Breed of a dog', 'animal-shelter' ) ),
			'cavalier-king-charles-spaniel'      => array( 'name' => _x( 'Cavalier King Charles Spaniel', 'Breed of a dog', 'animal-shelter' ) ),
			'cavapoo'                            => array( 'name' => _x( 'Cavapoo', 'Breed of a dog', 'animal-shelter' ) ),
			'central-asian-shepherd-dog'         => array( 'name' => _x( 'Central Asian Shepherd Dog', 'Breed of a dog', 'animal-shelter' ) ),
			'cesky-terrier'                      => array( 'name' => _x( 'Cesky Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'chabrador'                          => array( 'name' => _x( 'Chabrador', 'Breed of a dog', 'animal-shelter' ) ),
			'cheagle'                            => array( 'name' => _x( 'Cheagle', 'Breed of a dog', 'animal-shelter' ) ),
			'chesapeake-bay-retriever'           => array( 'name' => _x( 'Chesapeake Bay Retriever', 'Breed of a dog', 'animal-shelter' ) ),
			'chi-chi'                            => array( 'name' => _x( 'Chi Chi', 'Breed of a dog', 'animal-shelter' ) ),
			'chigi'                              => array( 'name' => _x( 'Chigi', 'Breed of a dog', 'animal-shelter' ) ),
			'chihuahua'                          => array( 'name' => _x( 'Chihuahua', 'Breed of a dog', 'animal-shelter' ) ),
			'chilier'                            => array( 'name' => _x( 'Chilier', 'Breed of a dog', 'animal-shelter' ) ),
			'chinese-crested'                    => array( 'name' => _x( 'Chinese Crested', 'Breed of a dog', 'animal-shelter' ) ),
			'chinese-shar-pei'                   => array( 'name' => _x( 'Chinese Shar-Pei', 'Breed of a dog', 'animal-shelter' ) ),
			'chinook'                            => array( 'name' => _x( 'Chinook', 'Breed of a dog', 'animal-shelter' ) ),
			'chion'                              => array( 'name' => _x( 'Chion', 'Breed of a dog', 'animal-shelter' ) ),
			'chipi'                              => array( 'name' => _x( 'Chipi', 'Breed of a dog', 'animal-shelter' ) ),
			'chi-poo'                            => array( 'name' => _x( 'Chi-Poo', 'Breed of a dog', 'animal-shelter' ) ),
			'chiweenie'                          => array( 'name' => _x( 'Chiweenie', 'Breed of a dog', 'animal-shelter' ) ),
			'chorkie'                            => array( 'name' => _x( 'Chorkie', 'Breed of a dog', 'animal-shelter' ) ),
			'chow-chow'                          => array( 'name' => _x( 'Chow Chow', 'Breed of a dog', 'animal-shelter' ) ),
			'chow-shepherd'                      => array( 'name' => _x( 'Chow Shepherd', 'Breed of a dog', 'animal-shelter' ) ),
			'chug'                               => array( 'name' => _x( 'Chug', 'Breed of a dog', 'animal-shelter' ) ),
			'chusky'                             => array( 'name' => _x( 'Chusky', 'Breed of a dog', 'animal-shelter' ) ),
			'cirneco-della-etna'                 => array( 'name' => _x( 'Cirneco dellâ\'Etna', 'Breed of a dog', 'animal-shelter' ) ),
			'clumber-spaniel'                    => array( 'name' => _x( 'Clumber Spaniel', 'Breed of a dog', 'animal-shelter' ) ),
			'cockalier'                          => array( 'name' => _x( 'Cockalier', 'Breed of a dog', 'animal-shelter' ) ),
			'cockapoo'                           => array( 'name' => _x( 'Cockapoo', 'Breed of a dog', 'animal-shelter' ) ),
			'cocker-spaniel'                     => array( 'name' => _x( 'Cocker Spaniel', 'Breed of a dog', 'animal-shelter' ) ),
			'collie'                             => array( 'name' => _x( 'Collie', 'Breed of a dog', 'animal-shelter' ) ),
			'corgi-inu'                          => array( 'name' => _x( 'Corgi Inu', 'Breed of a dog', 'animal-shelter' ) ),
			'corgidor'                           => array( 'name' => _x( 'Corgidor', 'Breed of a dog', 'animal-shelter' ) ),
			'corman-shepherd'                    => array( 'name' => _x( 'Corman Shepherd', 'Breed of a dog', 'animal-shelter' ) ),
			'coton-de-tulear'                    => array( 'name' => _x( 'Coton de Tulear', 'Breed of a dog', 'animal-shelter' ) ),
			'croatian-sheepdog'                  => array( 'name' => _x( 'Croatian Sheepdog', 'Breed of a dog', 'animal-shelter' ) ),
			'curly-coated-retriever'             => array( 'name' => _x( 'Curly-Coated Retriever', 'Breed of a dog', 'animal-shelter' ) ),
			'dachsador'                          => array( 'name' => _x( 'Dachsador', 'Breed of a dog', 'animal-shelter' ) ),
			'dachshund'                          => array( 'name' => _x( 'Dachshund', 'Breed of a dog', 'animal-shelter' ) ),
			'dalmatian'                          => array( 'name' => _x( 'Dalmatian', 'Breed of a dog', 'animal-shelter' ) ),
			'dandie-dinmont-terrier'             => array( 'name' => _x( 'Dandie Dinmont Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'daniff'                             => array( 'name' => _x( 'Daniff', 'Breed of a dog', 'animal-shelter' ) ),
			'danish-swedish-farmdog'             => array( 'name' => _x( 'Danish-Swedish Farmdog', 'Breed of a dog', 'animal-shelter' ) ),
			'deutscher-wachtelhund'              => array( 'name' => _x( 'Deutscher Wachtelhund', 'Breed of a dog', 'animal-shelter' ) ),
			'doberdor'                           => array( 'name' => _x( 'Doberdor', 'Breed of a dog', 'animal-shelter' ) ),
			'doberman-pinscher'                  => array( 'name' => _x( 'Doberman Pinscher', 'Breed of a dog', 'animal-shelter' ) ),
			'docker'                             => array( 'name' => _x( 'Docker', 'Breed of a dog', 'animal-shelter' ) ),
			'dogo-argentino'                     => array( 'name' => _x( 'Dogo Argentino', 'Breed of a dog', 'animal-shelter' ) ),
			'dogue-de-bordeaux'                  => array( 'name' => _x( 'Dogue de Bordeaux', 'Breed of a dog', 'animal-shelter' ) ),
			'dorgi'                              => array( 'name' => _x( 'Dorgi', 'Breed of a dog', 'animal-shelter' ) ),
			'dorkie'                             => array( 'name' => _x( 'Dorkie', 'Breed of a dog', 'animal-shelter' ) ),
			'doxiepoo'                           => array( 'name' => _x( 'Doxiepoo', 'Breed of a dog', 'animal-shelter' ) ),
			'doxle'                              => array( 'name' => _x( 'Doxle', 'Breed of a dog', 'animal-shelter' ) ),
			'drentsche-patrijshond'              => array( 'name' => _x( 'Drentsche Patrijshond', 'Breed of a dog', 'animal-shelter' ) ),
			'drever'                             => array( 'name' => _x( 'Drever', 'Breed of a dog', 'animal-shelter' ) ),
			'dutch-shepherd'                     => array( 'name' => _x( 'Dutch Shepherd', 'Breed of a dog', 'animal-shelter' ) ),
			'english-cocker-spaniel'             => array( 'name' => _x( 'English Cocker Spaniel', 'Breed of a dog', 'animal-shelter' ) ),
			'english-foxhound'                   => array( 'name' => _x( 'English Foxhound', 'Breed of a dog', 'animal-shelter' ) ),
			'english-setter'                     => array( 'name' => _x( 'English Setter', 'Breed of a dog', 'animal-shelter' ) ),
			'english-springer-spaniel'           => array( 'name' => _x( 'English Springer Spaniel', 'Breed of a dog', 'animal-shelter' ) ),
			'english-toy-spaniel'                => array( 'name' => _x( 'English Toy Spaniel', 'Breed of a dog', 'animal-shelter' ) ),
			'entlebucher-mountain-dog'           => array( 'name' => _x( 'Entlebucher Mountain Dog', 'Breed of a dog', 'animal-shelter' ) ),
			'estrela-mountain-dog'               => array( 'name' => _x( 'Estrela Mountain Dog', 'Breed of a dog', 'animal-shelter' ) ),
			'eurasier'                           => array( 'name' => _x( 'Eurasier', 'Breed of a dog', 'animal-shelter' ) ),
			'field-spaniel'                      => array( 'name' => _x( 'Field Spaniel', 'Breed of a dog', 'animal-shelter' ) ),
			'fila-brasileiro'                    => array( 'name' => _x( 'Fila Brasileiro', 'Breed of a dog', 'animal-shelter' ) ),
			'finnish-lapphund'                   => array( 'name' => _x( 'Finnish Lapphund', 'Breed of a dog', 'animal-shelter' ) ),
			'finnish-spitz'                      => array( 'name' => _x( 'Finnish Spitz', 'Breed of a dog', 'animal-shelter' ) ),
			'flat-coated-retriever'              => array( 'name' => _x( 'Flat-Coated Retriever', 'Breed of a dog', 'animal-shelter' ) ),
			'fox-terrier'                        => array( 'name' => _x( 'Fox Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'french-bulldog'                     => array( 'name' => _x( 'French Bulldog', 'Breed of a dog', 'animal-shelter' ) ),
			'french-bullhuahua'                  => array( 'name' => _x( 'French Bullhuahua', 'Breed of a dog', 'animal-shelter' ) ),
			'french-spaniel'                     => array( 'name' => _x( 'French Spaniel', 'Breed of a dog', 'animal-shelter' ) ),
			'frenchton'                          => array( 'name' => _x( 'Frenchton', 'Breed of a dog', 'animal-shelter' ) ),
			'frengle'                            => array( 'name' => _x( 'Frengle', 'Breed of a dog', 'animal-shelter' ) ),
			'german-longhaired-pointer'          => array( 'name' => _x( 'German Longhaired Pointer', 'Breed of a dog', 'animal-shelter' ) ),
			'german-pinscher'                    => array( 'name' => _x( 'German Pinscher', 'Breed of a dog', 'animal-shelter' ) ),
			'german-shepherd-dog'                => array( 'name' => _x( 'German Shepherd Dog', 'Breed of a dog', 'animal-shelter' ) ),
			'german-shepherd-pit-bull'           => array( 'name' => _x( 'German Shepherd Pit Bull', 'Breed of a dog', 'animal-shelter' ) ),
			'german-shepherd-rottweiler-mix'     => array( 'name' => _x( 'German Shepherd Rottweiler Mix', 'Breed of a dog', 'animal-shelter' ) ),
			'german-sheprador'                   => array( 'name' => _x( 'German Sheprador', 'Breed of a dog', 'animal-shelter' ) ),
			'german-shorthaired-pointer'         => array( 'name' => _x( 'German Shorthaired Pointer', 'Breed of a dog', 'animal-shelter' ) ),
			'german-spitz'                       => array( 'name' => _x( 'German Spitz', 'Breed of a dog', 'animal-shelter' ) ),
			'german-wirehaired-pointer'          => array( 'name' => _x( 'German Wirehaired Pointer', 'Breed of a dog', 'animal-shelter' ) ),
			'giant-schnauzer'                    => array( 'name' => _x( 'Giant Schnauzer', 'Breed of a dog', 'animal-shelter' ) ),
			'glen-of-imaal-terrier'              => array( 'name' => _x( 'Glen of Imaal Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'goberian'                           => array( 'name' => _x( 'Goberian', 'Breed of a dog', 'animal-shelter' ) ),
			'goldador'                           => array( 'name' => _x( 'Goldador', 'Breed of a dog', 'animal-shelter' ) ),
			'golden-cocker-retriever'            => array( 'name' => _x( 'Golden Cocker Retriever', 'Breed of a dog', 'animal-shelter' ) ),
			'golden-mountain-dog'                => array( 'name' => _x( 'Golden Mountain Dog', 'Breed of a dog', 'animal-shelter' ) ),
			'golden-retriever'                   => array( 'name' => _x( 'Golden Retriever', 'Breed of a dog', 'animal-shelter' ) ),
			'golden-retriever-corgi'             => array( 'name' => _x( 'Golden Retriever Corgi', 'Breed of a dog', 'animal-shelter' ) ),
			'golden-shepherd'                    => array( 'name' => _x( 'Golden Shepherd', 'Breed of a dog', 'animal-shelter' ) ),
			'goldendoodle'                       => array( 'name' => _x( 'Goldendoodle', 'Breed of a dog', 'animal-shelter' ) ),
			'gollie'                             => array( 'name' => _x( 'Gollie', 'Breed of a dog', 'animal-shelter' ) ),
			'gordon-setter'                      => array( 'name' => _x( 'Gordon Setter', 'Breed of a dog', 'animal-shelter' ) ),
			'great-dane'                         => array( 'name' => _x( 'Great Dane', 'Breed of a dog', 'animal-shelter' ) ),
			'great-pyrenees'                     => array( 'name' => _x( 'Great Pyrenees', 'Breed of a dog', 'animal-shelter' ) ),
			'greater-swiss-mountain-dog'         => array( 'name' => _x( 'Greater Swiss Mountain Dog', 'Breed of a dog', 'animal-shelter' ) ),
			'greyador'                           => array( 'name' => _x( 'Greyador', 'Breed of a dog', 'animal-shelter' ) ),
			'greyhound'                          => array( 'name' => _x( 'Greyhound', 'Breed of a dog', 'animal-shelter' ) ),
			'hamiltonstovare'                    => array( 'name' => _x( 'Hamiltonstovare', 'Breed of a dog', 'animal-shelter' ) ),
			'hanoverian-scenthound'              => array( 'name' => _x( 'Hanoverian Scenthound', 'Breed of a dog', 'animal-shelter' ) ),
			'harrier'                            => array( 'name' => _x( 'Harrier', 'Breed of a dog', 'animal-shelter' ) ),
			'havanese'                           => array( 'name' => _x( 'Havanese', 'Breed of a dog', 'animal-shelter' ) ),
			'havapoo'                            => array( 'name' => _x( 'Havapoo', 'Breed of a dog', 'animal-shelter' ) ),
			'hokkaido'                           => array( 'name' => _x( 'Hokkaido', 'Breed of a dog', 'animal-shelter' ) ),
			'horgi'                              => array( 'name' => _x( 'Horgi', 'Breed of a dog', 'animal-shelter' ) ),
			'hovawart'                           => array( 'name' => _x( 'Hovawart', 'Breed of a dog', 'animal-shelter' ) ),
			'huskita'                            => array( 'name' => _x( 'Huskita', 'Breed of a dog', 'animal-shelter' ) ),
			'huskydoodle'                        => array( 'name' => _x( 'Huskydoodle', 'Breed of a dog', 'animal-shelter' ) ),
			'ibizan-hound'                       => array( 'name' => _x( 'Ibizan Hound', 'Breed of a dog', 'animal-shelter' ) ),
			'icelandic-sheepdog'                 => array( 'name' => _x( 'Icelandic Sheepdog', 'Breed of a dog', 'animal-shelter' ) ),
			'irish-red-and-white-setter'         => array( 'name' => _x( 'Irish Red And White Setter', 'Breed of a dog', 'animal-shelter' ) ),
			'irish-setter'                       => array( 'name' => _x( 'Irish Setter', 'Breed of a dog', 'animal-shelter' ) ),
			'irish-terrier'                      => array( 'name' => _x( 'Irish Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'irish-water-spaniel'                => array( 'name' => _x( 'Irish Water Spaniel', 'Breed of a dog', 'animal-shelter' ) ),
			'irish-wolfhound'                    => array( 'name' => _x( 'Irish Wolfhound', 'Breed of a dog', 'animal-shelter' ) ),
			'italian-greyhound'                  => array( 'name' => _x( 'Italian Greyhound', 'Breed of a dog', 'animal-shelter' ) ),
			'jack-chi'                           => array( 'name' => _x( 'Jack Chi', 'Breed of a dog', 'animal-shelter' ) ),
			'jack-russell-terrier'               => array( 'name' => _x( 'Jack Russell Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'jack-a-poo'                         => array( 'name' => _x( 'Jack-A-Poo', 'Breed of a dog', 'animal-shelter' ) ),
			'jackshund'                          => array( 'name' => _x( 'Jackshund', 'Breed of a dog', 'animal-shelter' ) ),
			'japanese-chin'                      => array( 'name' => _x( 'Japanese Chin', 'Breed of a dog', 'animal-shelter' ) ),
			'japanese-spitz'                     => array( 'name' => _x( 'Japanese Spitz', 'Breed of a dog', 'animal-shelter' ) ),
			'kai-ken'                            => array( 'name' => _x( 'Kai Ken', 'Breed of a dog', 'animal-shelter' ) ),
			'karelian-bear-dog'                  => array( 'name' => _x( 'Karelian Bear Dog', 'Breed of a dog', 'animal-shelter' ) ),
			'keeshond'                           => array( 'name' => _x( 'Keeshond', 'Breed of a dog', 'animal-shelter' ) ),
			'kerry-blue-terrier'                 => array( 'name' => _x( 'Kerry Blue Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'king-shepherd'                      => array( 'name' => _x( 'King Shepherd', 'Breed of a dog', 'animal-shelter' ) ),
			'kishu-ken'                          => array( 'name' => _x( 'Kishu Ken', 'Breed of a dog', 'animal-shelter' ) ),
			'komondor'                           => array( 'name' => _x( 'Komondor', 'Breed of a dog', 'animal-shelter' ) ),
			'kooikerhondje'                      => array( 'name' => _x( 'Kooikerhondje', 'Breed of a dog', 'animal-shelter' ) ),
			'korean-jindo-dog'                   => array( 'name' => _x( 'Korean Jindo Dog', 'Breed of a dog', 'animal-shelter' ) ),
			'kuvasz'                             => array( 'name' => _x( 'Kuvasz', 'Breed of a dog', 'animal-shelter' ) ),
			'kyi-leo'                            => array( 'name' => _x( 'Kyi-Leo', 'Breed of a dog', 'animal-shelter' ) ),
			'lab-pointer'                        => array( 'name' => _x( 'Lab Pointer', 'Breed of a dog', 'animal-shelter' ) ),
			'labernese'                          => array( 'name' => _x( 'Labernese', 'Breed of a dog', 'animal-shelter' ) ),
			'labmaraner'                         => array( 'name' => _x( 'Labmaraner', 'Breed of a dog', 'animal-shelter' ) ),
			'labrabull'                          => array( 'name' => _x( 'Labrabull', 'Breed of a dog', 'animal-shelter' ) ),
			'labradane'                          => array( 'name' => _x( 'Labradane', 'Breed of a dog', 'animal-shelter' ) ),
			'labradoodle'                        => array( 'name' => _x( 'Labradoodle', 'Breed of a dog', 'animal-shelter' ) ),
			'labrador-retriever'                 => array( 'name' => _x( 'Labrador Retriever', 'Breed of a dog', 'animal-shelter' ) ),
			'labrastaff'                         => array( 'name' => _x( 'Labrastaff', 'Breed of a dog', 'animal-shelter' ) ),
			'labsky'                             => array( 'name' => _x( 'Labsky', 'Breed of a dog', 'animal-shelter' ) ),
			'lagotto-romagnolo'                  => array( 'name' => _x( 'Lagotto Romagnolo', 'Breed of a dog', 'animal-shelter' ) ),
			'lakeland-terrier'                   => array( 'name' => _x( 'Lakeland Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'lancashire-heeler'                  => array( 'name' => _x( 'Lancashire Heeler', 'Breed of a dog', 'animal-shelter' ) ),
			'leonberger'                         => array( 'name' => _x( 'Leonberger', 'Breed of a dog', 'animal-shelter' ) ),
			'lhasa-apso'                         => array( 'name' => _x( 'Lhasa Apso', 'Breed of a dog', 'animal-shelter' ) ),
			'lhasapoo'                           => array( 'name' => _x( 'Lhasapoo', 'Breed of a dog', 'animal-shelter' ) ),
			'lowchen'                            => array( 'name' => _x( 'Lowchen', 'Breed of a dog', 'animal-shelter' ) ),
			'maltese'                            => array( 'name' => _x( 'Maltese', 'Breed of a dog', 'animal-shelter' ) ),
			'maltese-shih-tzu'                   => array( 'name' => _x( 'Maltese Shih Tzu', 'Breed of a dog', 'animal-shelter' ) ),
			'maltipoo'                           => array( 'name' => _x( 'Maltipoo', 'Breed of a dog', 'animal-shelter' ) ),
			'manchester-terrier'                 => array( 'name' => _x( 'Manchester Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'maremma-sheepdog'                   => array( 'name' => _x( 'Maremma Sheepdog', 'Breed of a dog', 'animal-shelter' ) ),
			'mastador'                           => array( 'name' => _x( 'Mastador', 'Breed of a dog', 'animal-shelter' ) ),
			'mastiff'                            => array( 'name' => _x( 'Mastiff', 'Breed of a dog', 'animal-shelter' ) ),
			'miniature-pinscher'                 => array( 'name' => _x( 'Miniature Pinscher', 'Breed of a dog', 'animal-shelter' ) ),
			'miniature-schnauzer'                => array( 'name' => _x( 'Miniature Schnauzer', 'Breed of a dog', 'animal-shelter' ) ),
			'morkie'                             => array( 'name' => _x( 'Morkie', 'Breed of a dog', 'animal-shelter' ) ),
			'mountain-cur'                       => array( 'name' => _x( 'Mountain Cur', 'Breed of a dog', 'animal-shelter' ) ),
			'mountain-feist'                     => array( 'name' => _x( 'Mountain Feist', 'Breed of a dog', 'animal-shelter' ) ),
			'mudi'                               => array( 'name' => _x( 'Mudi', 'Breed of a dog', 'animal-shelter' ) ),
			'neapolitan-mastiff'                 => array( 'name' => _x( 'Neapolitan Mastiff', 'Breed of a dog', 'animal-shelter' ) ),
			'newfoundland'                       => array( 'name' => _x( 'Newfoundland', 'Breed of a dog', 'animal-shelter' ) ),
			'norfolk-terrier'                    => array( 'name' => _x( 'Norfolk Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'northern-inuit-dog'                 => array( 'name' => _x( 'Northern Inuit Dog', 'Breed of a dog', 'animal-shelter' ) ),
			'norwegian-buhund'                   => array( 'name' => _x( 'Norwegian Buhund', 'Breed of a dog', 'animal-shelter' ) ),
			'norwegian-elkhound'                 => array( 'name' => _x( 'Norwegian Elkhound', 'Breed of a dog', 'animal-shelter' ) ),
			'norwegian-lundehund'                => array( 'name' => _x( 'Norwegian Lundehund', 'Breed of a dog', 'animal-shelter' ) ),
			'norwich-terrier'                    => array( 'name' => _x( 'Norwich Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'nova-scotia-duck-tolling-retriever' => array( 'name' => _x( 'Nova Scotia Duck Tolling Retriever', 'Breed of a dog', 'animal-shelter' ) ),
			'old-english-sheepdog'               => array( 'name' => _x( 'Old English Sheepdog', 'Breed of a dog', 'animal-shelter' ) ),
			'otterhound'                         => array( 'name' => _x( 'Otterhound', 'Breed of a dog', 'animal-shelter' ) ),
			'papillon'                           => array( 'name' => _x( 'Papillon', 'Breed of a dog', 'animal-shelter' ) ),
			'papipoo'                            => array( 'name' => _x( 'Papipoo', 'Breed of a dog', 'animal-shelter' ) ),
			'patterdale-terrier'                 => array( 'name' => _x( 'Patterdale Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'peekapoo'                           => array( 'name' => _x( 'Peekapoo', 'Breed of a dog', 'animal-shelter' ) ),
			'pekingese'                          => array( 'name' => _x( 'Pekingese', 'Breed of a dog', 'animal-shelter' ) ),
			'pembroke-welsh-corgi'               => array( 'name' => _x( 'Pembroke Welsh Corgi', 'Breed of a dog', 'animal-shelter' ) ),
			'petit basset griffon vend-en'       => array( 'name' => _x( 'Petit Basset Griffon Vend\'en', 'Breed of a dog', 'animal-shelter' ) ),
			'pharaoh-hound'                      => array( 'name' => _x( 'Pharaoh Hound', 'Breed of a dog', 'animal-shelter' ) ),
			'pitsky'                             => array( 'name' => _x( 'Pitsky', 'Breed of a dog', 'animal-shelter' ) ),
			'plott'                              => array( 'name' => _x( 'Plott', 'Breed of a dog', 'animal-shelter' ) ),
			'pocket-beagle'                      => array( 'name' => _x( 'Pocket Beagle', 'Breed of a dog', 'animal-shelter' ) ),
			'pointer'                            => array( 'name' => _x( 'Pointer', 'Breed of a dog', 'animal-shelter' ) ),
			'polish-lowland-sheepdog'            => array( 'name' => _x( 'Polish Lowland Sheepdog', 'Breed of a dog', 'animal-shelter' ) ),
			'pomapoo'                            => array( 'name' => _x( 'Pomapoo', 'Breed of a dog', 'animal-shelter' ) ),
			'pomchi'                             => array( 'name' => _x( 'Pomchi', 'Breed of a dog', 'animal-shelter' ) ),
			'pomeagle'                           => array( 'name' => _x( 'Pomeagle', 'Breed of a dog', 'animal-shelter' ) ),
			'pomeranian'                         => array( 'name' => _x( 'Pomeranian', 'Breed of a dog', 'animal-shelter' ) ),
			'pomsky'                             => array( 'name' => _x( 'Pomsky', 'Breed of a dog', 'animal-shelter' ) ),
			'poochon'                            => array( 'name' => _x( 'Poochon', 'Breed of a dog', 'animal-shelter' ) ),
			'poodle'                             => array( 'name' => _x( 'Poodle', 'Breed of a dog', 'animal-shelter' ) ),
			'portuguese-podengo-pequeno'         => array( 'name' => _x( 'Portuguese Podengo Pequeno', 'Breed of a dog', 'animal-shelter' ) ),
			'portuguese-pointer'                 => array( 'name' => _x( 'Portuguese Pointer', 'Breed of a dog', 'animal-shelter' ) ),
			'portuguese-sheepdog'                => array( 'name' => _x( 'Portuguese Sheepdog', 'Breed of a dog', 'animal-shelter' ) ),
			'portuguese-water-dog'               => array( 'name' => _x( 'Portuguese Water Dog', 'Breed of a dog', 'animal-shelter' ) ),
			'pudelpointer'                       => array( 'name' => _x( 'Pudelpointer', 'Breed of a dog', 'animal-shelter' ) ),
			'pug'                                => array( 'name' => _x( 'Pug', 'Breed of a dog', 'animal-shelter' ) ),
			'pugalier'                           => array( 'name' => _x( 'Pugalier', 'Breed of a dog', 'animal-shelter' ) ),
			'puggle'                             => array( 'name' => _x( 'Puggle', 'Breed of a dog', 'animal-shelter' ) ),
			'puginese'                           => array( 'name' => _x( 'Puginese', 'Breed of a dog', 'animal-shelter' ) ),
			'puli'                               => array( 'name' => _x( 'Puli', 'Breed of a dog', 'animal-shelter' ) ),
			'pyredoodle'                         => array( 'name' => _x( 'Pyredoodle', 'Breed of a dog', 'animal-shelter' ) ),
			'pyrenean-mastiff'                   => array( 'name' => _x( 'Pyrenean Mastiff', 'Breed of a dog', 'animal-shelter' ) ),
			'pyrenean-shepherd'                  => array( 'name' => _x( 'Pyrenean Shepherd', 'Breed of a dog', 'animal-shelter' ) ),
			'rat-terrier'                        => array( 'name' => _x( 'Rat Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'redbone-coonhound'                  => array( 'name' => _x( 'Redbone Coonhound', 'Breed of a dog', 'animal-shelter' ) ),
			'rhodesian-ridgeback'                => array( 'name' => _x( 'Rhodesian Ridgeback', 'Breed of a dog', 'animal-shelter' ) ),
			'rottador'                           => array( 'name' => _x( 'Rottador', 'Breed of a dog', 'animal-shelter' ) ),
			'rottle'                             => array( 'name' => _x( 'Rottle', 'Breed of a dog', 'animal-shelter' ) ),
			'rottweiler'                         => array( 'name' => _x( 'Rottweiler', 'Breed of a dog', 'animal-shelter' ) ),
			'saint-berdoodle'                    => array( 'name' => _x( 'Saint Berdoodle', 'Breed of a dog', 'animal-shelter' ) ),
			'saint-bernard'                      => array( 'name' => _x( 'Saint Bernard', 'Breed of a dog', 'animal-shelter' ) ),
			'saluki'                             => array( 'name' => _x( 'Saluki', 'Breed of a dog', 'animal-shelter' ) ),
			'samoyed'                            => array( 'name' => _x( 'Samoyed', 'Breed of a dog', 'animal-shelter' ) ),
			'samusky'                            => array( 'name' => _x( 'Samusky', 'Breed of a dog', 'animal-shelter' ) ),
			'schipperke'                         => array( 'name' => _x( 'Schipperke', 'Breed of a dog', 'animal-shelter' ) ),
			'schnoodle'                          => array( 'name' => _x( 'Schnoodle', 'Breed of a dog', 'animal-shelter' ) ),
			'scottish-deerhound'                 => array( 'name' => _x( 'Scottish Deerhound', 'Breed of a dog', 'animal-shelter' ) ),
			'scottish-terrier'                   => array( 'name' => _x( 'Scottish Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'sealyham-terrier'                   => array( 'name' => _x( 'Sealyham Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'sheepadoodle'                       => array( 'name' => _x( 'Sheepadoodle', 'Breed of a dog', 'animal-shelter' ) ),
			'shepsky'                            => array( 'name' => _x( 'Shepsky', 'Breed of a dog', 'animal-shelter' ) ),
			'shetland-sheepdog'                  => array( 'name' => _x( 'Shetland Sheepdog', 'Breed of a dog', 'animal-shelter' ) ),
			'shiba-inu'                          => array( 'name' => _x( 'Shiba Inu', 'Breed of a dog', 'animal-shelter' ) ),
			'shichon'                            => array( 'name' => _x( 'Shichon', 'Breed of a dog', 'animal-shelter' ) ),
			'shih-tzu'                           => array( 'name' => _x( 'Shih Tzu', 'Breed of a dog', 'animal-shelter' ) ),
			'shih-poo'                           => array( 'name' => _x( 'Shih-Poo', 'Breed of a dog', 'animal-shelter' ) ),
			'shikoku'                            => array( 'name' => _x( 'Shikoku', 'Breed of a dog', 'animal-shelter' ) ),
			'shiloh-shepherd'                    => array( 'name' => _x( 'Shiloh Shepherd', 'Breed of a dog', 'animal-shelter' ) ),
			'shiranian'                          => array( 'name' => _x( 'Shiranian', 'Breed of a dog', 'animal-shelter' ) ),
			'shollie'                            => array( 'name' => _x( 'Shollie', 'Breed of a dog', 'animal-shelter' ) ),
			'shorkie'                            => array( 'name' => _x( 'Shorkie', 'Breed of a dog', 'animal-shelter' ) ),
			'siberian-husky'                     => array( 'name' => _x( 'Siberian Husky', 'Breed of a dog', 'animal-shelter' ) ),
			'silken-windhound'                   => array( 'name' => _x( 'Silken Windhound', 'Breed of a dog', 'animal-shelter' ) ),
			'silky-terrier'                      => array( 'name' => _x( 'Silky Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'skye-terrier'                       => array( 'name' => _x( 'Skye Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'sloughi'                            => array( 'name' => _x( 'Sloughi', 'Breed of a dog', 'animal-shelter' ) ),
			'small-munsterlander-pointer'        => array( 'name' => _x( 'Small Munsterlander Pointer', 'Breed of a dog', 'animal-shelter' ) ),
			'soft-coated-wheaten-terrier'        => array( 'name' => _x( 'Soft Coated Wheaten Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'spanish-mastiff'                    => array( 'name' => _x( 'Spanish Mastiff', 'Breed of a dog', 'animal-shelter' ) ),
			'spinone-italiano'                   => array( 'name' => _x( 'Spinone Italiano', 'Breed of a dog', 'animal-shelter' ) ),
			'springador'                         => array( 'name' => _x( 'Springador', 'Breed of a dog', 'animal-shelter' ) ),
			'stabyhoun'                          => array( 'name' => _x( 'Stabyhoun', 'Breed of a dog', 'animal-shelter' ) ),
			'staffordshire-bull-terrier'         => array( 'name' => _x( 'Staffordshire Bull Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'staffy-bull-bullmastiff'            => array( 'name' => _x( 'Staffy Bull Bullmastiff', 'Breed of a dog', 'animal-shelter' ) ),
			'standard-schnauzer'                 => array( 'name' => _x( 'Standard Schnauzer', 'Breed of a dog', 'animal-shelter' ) ),
			'sussex-spaniel'                     => array( 'name' => _x( 'Sussex Spaniel', 'Breed of a dog', 'animal-shelter' ) ),
			'swedish-lapphund'                   => array( 'name' => _x( 'Swedish Lapphund', 'Breed of a dog', 'animal-shelter' ) ),
			'swedish-vallhund'                   => array( 'name' => _x( 'Swedish Vallhund', 'Breed of a dog', 'animal-shelter' ) ),
			'taiwan-dog'                         => array( 'name' => _x( 'Taiwan Dog', 'Breed of a dog', 'animal-shelter' ) ),
			'terripoo'                           => array( 'name' => _x( 'Terripoo', 'Breed of a dog', 'animal-shelter' ) ),
			'texas-heeler'                       => array( 'name' => _x( 'Texas Heeler', 'Breed of a dog', 'animal-shelter' ) ),
			'thai-ridgeback'                     => array( 'name' => _x( 'Thai Ridgeback', 'Breed of a dog', 'animal-shelter' ) ),
			'tibetan-mastiff'                    => array( 'name' => _x( 'Tibetan Mastiff', 'Breed of a dog', 'animal-shelter' ) ),
			'tibetan-spaniel'                    => array( 'name' => _x( 'Tibetan Spaniel', 'Breed of a dog', 'animal-shelter' ) ),
			'tibetan-terrier'                    => array( 'name' => _x( 'Tibetan Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'toy-fox-terrier'                    => array( 'name' => _x( 'Toy Fox Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'transylvanian-hound'                => array( 'name' => _x( 'Transylvanian Hound', 'Breed of a dog', 'animal-shelter' ) ),
			'treeing-tennessee-brindle'          => array( 'name' => _x( 'Treeing Tennessee Brindle', 'Breed of a dog', 'animal-shelter' ) ),
			'treeing-walker-coonhound'           => array( 'name' => _x( 'Treeing Walker Coonhound', 'Breed of a dog', 'animal-shelter' ) ),
			'valley-bulldog'                     => array( 'name' => _x( 'Valley Bulldog', 'Breed of a dog', 'animal-shelter' ) ),
			'vizsla'                             => array( 'name' => _x( 'Vizsla', 'Breed of a dog', 'animal-shelter' ) ),
			'weimaraner'                         => array( 'name' => _x( 'Weimaraner', 'Breed of a dog', 'animal-shelter' ) ),
			'welsh-springer-spaniel'             => array( 'name' => _x( 'Welsh Springer Spaniel', 'Breed of a dog', 'animal-shelter' ) ),
			'welsh-terrier'                      => array( 'name' => _x( 'Welsh Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'west-highland-white-terrier'        => array( 'name' => _x( 'West Highland White Terrier', 'Breed of a dog', 'animal-shelter' ) ),
			'westiepoo'                          => array( 'name' => _x( 'Westiepoo', 'Breed of a dog', 'animal-shelter' ) ),
			'whippet'                            => array( 'name' => _x( 'Whippet', 'Breed of a dog', 'animal-shelter' ) ),
			'whoodle'                            => array( 'name' => _x( 'Whoodle', 'Breed of a dog', 'animal-shelter' ) ),
			'wirehaired-pointing-griffon'        => array( 'name' => _x( 'Wirehaired Pointing Griffon', 'Breed of a dog', 'animal-shelter' ) ),
			'xoloitzcuintli'                     => array( 'name' => _x( 'Xoloitzcuintli', 'Breed of a dog', 'animal-shelter' ) ),
			'yakutian-laika'                     => array( 'name' => _x( 'Yakutian Laika', 'Breed of a dog', 'animal-shelter' ) ),
			'yorkipoo'                           => array( 'name' => _x( 'Yorkipoo', 'Breed of a dog', 'animal-shelter' ) ),
			'yorkshire-terrier'                  => array( 'name' => _x( 'Yorkshire Terrier', 'Breed of a dog', 'animal-shelter' ) ),
		);

	}

	public function get_select_array(): array {
		// TODO
	}

	public function get_name( $key ): string {
		// TODO
	}
}
